apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-grpc-service
  template:
    metadata:
      labels:
        app: my-grpc-service
    spec:
      containers:
        - name: my-service # Noncompliant
          image: my-grpc-service:3.11
          resources:
            requests:
              memory: 100Mi
              cpu: "0.5"
              ephemeral-storage: "2Gi"
            limits:
              ephemeral-storage: "2Gi"
              memory: 100Mi
          volumeMounts:
            - name: ephemeral
              mountPath: "/app"
          ports:
            - containerPort: 50051
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_url
      automountServiceAccountToken: false